#!/bin/bash
set -e

# Reload systemd to recognize the new service 
systemctl daemon-reload
# Enable and start the service
systemctl enable kernel-autotune.service
systemctl start kernel-autotune.service

exit 0
